name: "000_dbn_lr2e4_REDS_e301_B8G1_s"

__base_cfg__: ./../../base_reds.yaml

dataset:
    train:
        # dataloader per GPU
        loader:
            batch_size: 4
            num_workers: 8

model:
    name: "DBN"
    num_frames: 5
    in_channels: 3
    inner_channels: 64

loss: 
    name: CharbonnierLoss

schedule: 
    epochs: 301
    val_epochs: 2
    
    optimizer:
        name: "Adam"
        lr: 0.0002
        betas: [0.9, 0.99]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [250, 280, 290]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/dbn"
resume_from: None