name: "000_IFIRNN_C2H3_lr2e4_DVD_e651_B8G4_s"

dataset:
    train:
        name: "DVD"
        mode: "train"
        
        sampling: "n_n"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: True
        interval: 1
        
        root_gt: "./datasets/DVD/quantitative_datasets"
        data_type: "imgs"
        num_frames: 12
        
        # augmentations
        augmentation:
            RandomCrop: 
                size : [256, 256]
            RandomHorizontalFlip: 
                p: 0.5
            RandomVerticalFlip: 
                p: 0.5
            RandomRotation90: 
                p: 0.5
            # RandomReverse: 
            #     p: 0.5
        
        loader:
            batch_size: 4
            num_workers: 8
            

    val:
        name: "DVD"
        mode: "val"
        
        sampling: "n_n"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: False 
        interval: 1
        
        root_gt: "./datasets/DVD/test"
        data_type: "imgs"
        num_frames: 12

        loader:
            batch_size: 1
            num_workers: 1

    
    test:
        name: "DVD"
        mode: "val"
        
        sampling: "n_n"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: False 
        interval: 1
        
        root_gt: "./datasets/DVD/test"
        data_type: "imgs"
        num_frames: 12

        loader:
            batch_size: 1
            num_workers: 1


model:
    name: "IFIRNN"
    in_channels: 3
    inner_channels: 16
    dual_cell: True
    intra_iters: 3

loss: 
    name: CharbonnierLoss

schedule: 
    epochs: 651
    val_epochs: 5
    
    optimizer:
        name: "Adam"
        lr: 0.0002
        betas: [0.9, 0.99]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [500, 600, 620]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/IFIRNN"
resume_from: None